### ISSUE TITLE
Sensori senza Valore

### ISSUE THREAD

**Issue by FranFabi** [sdesalve/zcsazzurro#20]
Salve, dopo aver installato l'integrazione e creato i sensori mi trovo nella situazione come in foto. In pratica tutti i sensori sono vuoti. 
![Image 001](https://user-images.githubusercontent.com/101736355/209672609-2aa56938-7807-4be5-af24-cc267dad78c7.png)

Quale potrebbe essere il problema ?

**Comment by sdesalve** [comment]
Nel log c'è scritto il problema...

**Comment by FranFabi** [comment]
Grazie della risposta, ma non riesco a trovare niente nei log di HA

**Comment by sdesalve** [comment]
Metti/integra con il logger esistente nel tuo configuration.yaml

```
logger:
  default: error
  logs:
    homeassistant.components.rest: debug
    homeassistant.components.rest.data: debug
    custom_components.zcsazzurro: debug
    custom_components.zcsazzurro.sensor: debug
```
